### ISSUE TITLE
Character limit on Project Editing - Problem Statement field

### ISSUE THREAD

**Issue by daleinen7** [code-312/Voma#134]
![Image](https://github.com/code-312/Voma/assets/6326891/f6825d4f-8a4e-4e6d-825a-8da6d642527c)

Adding 352 characters to the Problem Statement field return a 400 error from the server rather than saving to the database. 

We need to:
 - Identify what is causing that
 - Update it so that we can have something closer to 1000 character limit

**Comment by raindogg** [comment]
I updated `description`, `tech`, `goodFitFor`, `comment` and `projectStatement` to all be type TEXT, which doesn't have the 255 limit that STRING type (apparently) does.
